Comment out repository existence check in create-repo.yml

diff --git a/.github/workflows/create-repo.yml b/.github/workflows/create-repo.yml
--- a/.github/workflows/create-repo.yml
+++ b/.github/workflows/create-repo.yml
@@ -30,22 +30,22 @@ jobs:
           ## Todo write this to the issue, maybe allow a /rerun command
 
       # Check if repo by the name already exists and notify in issue/exit if it does
-      - name: Checking for repo existance
-        id: checkRepo
-        env:
-          GH_TOKEN: ${{ secrets.PAT }}
-        run: |
-          gh api /repos/${{ env.ORG }}/${{ steps.issue-parser.outputs.issueparser_repo-name }} > /dev/null
-          if [ $? -eq 0 ]; then
-            echo "Repository already exists"
-            gh issue comment ${{ github.event.issue.number }} --body "The repository already exists. Please try again with a different name."
-            exit 1
-          fi
+      # - name: Checking for repo existance
+      #   id: checkRepo
+      #   env:
+      #     GH_TOKEN: ${{ secrets.PAT }}
+      #   run: |
+      #     gh api /repos/${{ env.ORG }}/${{ steps.issue-parser.outputs.issueparser_repo-name }} > /dev/null
+      #     if [ $? -eq 0 ]; then
+      #       echo "Repository already exists"
+      #       gh issue comment ${{ github.event.issue.number }} --body "The repository already exists. Please try again with a different name."
+      #       exit 1
+      #     fi
       
       - name: Create repo
         id: createRepo
         continue-on-error: true
-        if: steps.checkRepo.outcome == 'failure'
+        # if: steps.checkRepo.outcome == 'failure'
         env:
           GITHUB_TOKEN: ${{ secrets.PAT }}
         run: |
